// <auto-generated />
namespace ProjectS360.MODEL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class App : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(App));
        
        string IMigrationMetadata.Id
        {
            get { return "202010150616386_App"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
